// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCffXe7dV6tN6jhQ55FLLrctWjMC2egt44',
    appId: '1:320279152510:web:755b48ef3171d0ac2f552f',
    messagingSenderId: '320279152510',
    projectId: 'income-expense-note',
    authDomain: 'income-expense-note.firebaseapp.com',
    storageBucket: 'income-expense-note.appspot.com',
    measurementId: 'G-S6LN0N9XEC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwx02Eozq4MUcG_l73myLDUBzv1-krvxw',
    appId: '1:320279152510:android:3fe6d3bf2d01432f2f552f',
    messagingSenderId: '320279152510',
    projectId: 'income-expense-note',
    storageBucket: 'income-expense-note.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7xj51M16RWomUahGOZXtraXPuuQmAWfk',
    appId: '1:320279152510:ios:9dd43691ad33f53c2f552f',
    messagingSenderId: '320279152510',
    projectId: 'income-expense-note',
    storageBucket: 'income-expense-note.appspot.com',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7xj51M16RWomUahGOZXtraXPuuQmAWfk',
    appId: '1:320279152510:ios:6e93d6e6345cd2202f552f',
    messagingSenderId: '320279152510',
    projectId: 'income-expense-note',
    storageBucket: 'income-expense-note.appspot.com',
    iosBundleId: 'com.example.assignment.RunnerTests',
  );
}
